//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave_1._0.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave_1._0.Properties.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le nom de votre sauvegarde.
        /// </summary>
        internal static string ask_name_save {
            get {
                return ResourceManager.GetString("ask_name_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le type de sauvegarde :.
        /// </summary>
        internal static string ask_save_type {
            get {
                return ResourceManager.GetString("ask_save_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le chemin du dossier à sauvegarder.
        /// </summary>
        internal static string ask_source_path {
            get {
                return ResourceManager.GetString("ask_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez le chemin du dossier dans lequel sauvegarder.
        /// </summary>
        internal static string ask_target_path {
            get {
                return ResourceManager.GetString("ask_target_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue de l&apos;application est le français.
        /// </summary>
        internal static string check_language {
            get {
                return ResourceManager.GetString("check_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner votre action parmi les choix suivants.
        /// </summary>
        internal static string choose_action {
            get {
                return ResourceManager.GetString("choose_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indiquez la sauvegarde concernée :.
        /// </summary>
        internal static string choose_save {
            get {
                return ResourceManager.GetString("choose_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer la sauvegarde {0}.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde {0} a bien été supprimée..
        /// </summary>
        internal static string delete_end {
            get {
                return ResourceManager.GetString("delete_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde différentielle : sauvegarder uniquement les fichiers différents..
        /// </summary>
        internal static string differentiel_save {
            get {
                return ResourceManager.GetString("differentiel_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À bientôt.
        /// </summary>
        internal static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        internal static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner votre langue parmi les choix proposés.
        /// </summary>
        internal static string language_choose {
            get {
                return ResourceManager.GetString("language_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string language_en {
            get {
                return ResourceManager.GetString("language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string language_fr {
            get {
                return ResourceManager.GetString("language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une sauvegarde.
        /// </summary>
        internal static string list_create_save {
            get {
                return ResourceManager.GetString("list_create_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer une sauvegarde.
        /// </summary>
        internal static string list_delete_save {
            get {
                return ResourceManager.GetString("list_delete_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter l&apos;application.
        /// </summary>
        internal static string list_exit {
            get {
                return ResourceManager.GetString("list_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter toutes les sauvegardes.
        /// </summary>
        internal static string list_run_all {
            get {
                return ResourceManager.GetString("list_run_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter une sauvegarde.
        /// </summary>
        internal static string list_run_one {
            get {
                return ResourceManager.GetString("list_run_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde {0} n&apos;existe pas. Vérifiez votre choix..
        /// </summary>
        internal static string notsave_found {
            get {
                return ResourceManager.GetString("notsave_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de lancer toutes les sauvegardes..
        /// </summary>
        internal static string run_all_save {
            get {
                return ResourceManager.GetString("run_all_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de lancer une sauvegarde.
        /// </summary>
        internal static string run_onesave {
            get {
                return ResourceManager.GetString("run_onesave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de créer une sauvegarde .
        /// </summary>
        internal static string save_create_chosen {
            get {
                return ResourceManager.GetString("save_create_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde {0} crée.
        /// </summary>
        internal static string save_created {
            get {
                return ResourceManager.GetString("save_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez choisi de supprimer une sauvegarde.
        /// </summary>
        internal static string save_delete_chosen {
            get {
                return ResourceManager.GetString("save_delete_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde {0} en cours....
        /// </summary>
        internal static string save_loading {
            get {
                return ResourceManager.GetString("save_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde {0} exécutée.
        /// </summary>
        internal static string save_run {
            get {
                return ResourceManager.GetString("save_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde totale : sauvegarder l&apos;intégralité des fichiers..
        /// </summary>
        internal static string total_save {
            get {
                return ResourceManager.GetString("total_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez atteint le nombre de sauvegarde maximum. Veuillez supprimer des sauvegardes.
        /// </summary>
        internal static string warning_toomuchsave {
            get {
                return ResourceManager.GetString("warning_toomuchsave", resourceCulture);
            }
        }
    }
}
